import type { Project, Task } from './types';

export const sampleProject: Project = {
  id: 'public-app-launch',
  name: 'Public App Launch',
  objective: 'Ship a small public Critical Path Mapper MVP that is useful, polished, and portfolio-ready.',
  createdAt: '2026-05-26T00:00:00.000Z',
  updatedAt: '2026-05-26T00:00:00.000Z',
};

export const sampleTasks: Task[] = [
  {
    id: 'repo-shell',
    projectId: sampleProject.id,
    title: 'Create public repo shell',
    description: 'Initialize the repository with README, docs, roadmap, and license.',
    status: 'done',
    dependsOn: [],
    effort: 1,
    impact: 5,
    urgency: 4,
    risk: 2,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'data-model',
    projectId: sampleProject.id,
    title: 'Define project and task model',
    description: 'Create TypeScript types for projects, tasks, status, dependencies, and scoring.',
    status: 'done',
    dependsOn: ['repo-shell'],
    effort: 2,
    impact: 5,
    urgency: 4,
    risk: 3,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'sample-data',
    projectId: sampleProject.id,
    title: 'Add sample project data',
    description: 'Include realistic demo tasks so visitors can understand the app instantly.',
    status: 'done',
    dependsOn: ['data-model'],
    effort: 1,
    impact: 4,
    urgency: 4,
    risk: 2,
    canParallelize: true,
    isActiveDamage: false,
  },
  {
    id: 'analysis-engine',
    projectId: sampleProject.id,
    title: 'Build priority and blocker analysis engine',
    description: 'Calculate priority score, dependent counts, blocked status, and fast-track candidates.',
    status: 'in_progress',
    dependsOn: ['data-model', 'sample-data'],
    effort: 3,
    impact: 5,
    urgency: 5,
    risk: 4,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'dashboard-ui',
    projectId: sampleProject.id,
    title: 'Render dashboard cards',
    description: 'Show next best action, top blocker, blocked tasks, and fast-track work.',
    status: 'ready',
    dependsOn: ['analysis-engine'],
    effort: 3,
    impact: 5,
    urgency: 4,
    risk: 3,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'task-board',
    projectId: sampleProject.id,
    title: 'Render task board',
    description: 'Group tasks by critical path, ready, blocked, fast-track, not-now, and done.',
    status: 'ready',
    dependsOn: ['analysis-engine'],
    effort: 3,
    impact: 4,
    urgency: 3,
    risk: 2,
    canParallelize: true,
    isActiveDamage: false,
  },
  {
    id: 'export-markdown',
    projectId: sampleProject.id,
    title: 'Add markdown export',
    description: 'Generate a copyable action plan from the current project analysis.',
    status: 'ready',
    dependsOn: ['analysis-engine'],
    effort: 2,
    impact: 4,
    urgency: 3,
    risk: 2,
    canParallelize: true,
    isActiveDamage: false,
  },
  {
    id: 'deploy',
    projectId: sampleProject.id,
    title: 'Deploy public MVP',
    description: 'Publish the static app and add the deployment link to the README.',
    status: 'blocked',
    dependsOn: ['dashboard-ui', 'task-board', 'export-markdown'],
    effort: 2,
    impact: 5,
    urgency: 3,
    risk: 3,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'portfolio-writeup',
    projectId: sampleProject.id,
    title: 'Write short portfolio case study',
    description: 'Explain the problem, design choices, tradeoffs, and next steps.',
    status: 'ready',
    dependsOn: ['repo-shell'],
    effort: 2,
    impact: 4,
    urgency: 2,
    risk: 1,
    canParallelize: true,
    isActiveDamage: false,
  },
];
