import type { Project, Task } from './types';

export const sampleProject: Project = {
  id: 'public-app-launch',
  name: 'Public App Launch',
  objective: 'Ship a small public Critical Path Mapper MVP that is useful, polished, and portfolio-ready.',
  createdAt: '2026-05-26T00:00:00.000Z',
  updatedAt: '2026-05-26T00:00:00.000Z',
};

export const sampleTasks: Task[] = [
  {
    id: 'repo-shell',
    projectId: sampleProject.id,
    title: 'Create public repo shell',
    description: 'Initialize the repository with README, docs, roadmap, and license.',
    startDay: 1,
    durationDays: 1,
    phase: 'stabilize',
    status: 'done',
    dependsOn: [],
    effort: 1,
    impact: 5,
    urgency: 4,
    risk: 2,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'data-model',
    projectId: sampleProject.id,
    title: 'Define project and task model',
    description: 'Create TypeScript types for projects, tasks, status, dependencies, and scoring.',
    startDay: 1,
    durationDays: 2,
    phase: 'build',
    status: 'done',
    dependsOn: ['repo-shell'],
    effort: 2,
    impact: 5,
    urgency: 4,
    risk: 3,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'sample-data',
    projectId: sampleProject.id,
    title: 'Add sample project data',
    description: 'Include realistic demo tasks so visitors can understand the app instantly.',
    startDay: 2,
    durationDays: 1,
    phase: 'build',
    status: 'done',
    dependsOn: ['data-model'],
    effort: 1,
    impact: 4,
    urgency: 4,
    risk: 2,
    canParallelize: true,
    isActiveDamage: false,
  },
  {
    id: 'analysis-engine',
    projectId: sampleProject.id,
    title: 'Build priority and blocker analysis engine',
    description: 'Calculate priority score, dependent counts, blocked status, and fast-track candidates.',
    startDay: 2,
    durationDays: 3,
    phase: 'build',
    status: 'in_progress',
    dependsOn: ['data-model', 'sample-data'],
    effort: 3,
    impact: 5,
    urgency: 5,
    risk: 4,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'route-regression',
    projectId: sampleProject.id,
    title: 'Fix demo route regression',
    description: 'Stop broken static routing from compounding launch risk.',
    startDay: 3,
    durationDays: 2,
    phase: 'stabilize',
    status: 'in_progress',
    dependsOn: ['repo-shell'],
    effort: 2,
    impact: 5,
    urgency: 5,
    risk: 5,
    canParallelize: true,
    isActiveDamage: true,
  },
  {
    id: 'dashboard-ui',
    projectId: sampleProject.id,
    title: 'Render dashboard cards',
    description: 'Show the command summary, timeline entry points, blockers, and fast-track work.',
    startDay: 4,
    durationDays: 2,
    phase: 'polish',
    status: 'ready',
    dependsOn: ['analysis-engine'],
    effort: 3,
    impact: 5,
    urgency: 4,
    risk: 3,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'task-board',
    projectId: sampleProject.id,
    title: 'Render task board',
    description: 'Group tasks by critical path, blockers, fast-track work, and done.',
    startDay: 4,
    durationDays: 2,
    phase: 'polish',
    status: 'ready',
    dependsOn: ['analysis-engine'],
    effort: 3,
    impact: 4,
    urgency: 3,
    risk: 2,
    canParallelize: true,
    isActiveDamage: false,
  },
  {
    id: 'export-markdown',
    projectId: sampleProject.id,
    title: 'Add markdown export',
    description: 'Generate a copyable action plan from the current project analysis.',
    startDay: 5,
    durationDays: 1,
    phase: 'polish',
    status: 'ready',
    dependsOn: ['analysis-engine'],
    effort: 2,
    impact: 4,
    urgency: 3,
    risk: 2,
    canParallelize: true,
    isActiveDamage: false,
  },
  {
    id: 'deploy',
    projectId: sampleProject.id,
    title: 'Deploy public MVP',
    description: 'Publish the static app and add the deployment link to the README.',
    startDay: 7,
    durationDays: 1,
    phase: 'deploy',
    status: 'blocked',
    dependsOn: ['dashboard-ui', 'task-board', 'export-markdown', 'route-regression'],
    effort: 2,
    impact: 5,
    urgency: 3,
    risk: 3,
    canParallelize: false,
    isActiveDamage: false,
  },
  {
    id: 'portfolio-writeup',
    projectId: sampleProject.id,
    title: 'Write short portfolio case study',
    description: 'Explain the problem, design choices, tradeoffs, and next steps.',
    startDay: 5,
    durationDays: 2,
    phase: 'polish',
    status: 'ready',
    dependsOn: ['repo-shell'],
    effort: 2,
    impact: 4,
    urgency: 2,
    risk: 1,
    canParallelize: true,
    isActiveDamage: false,
  },
];
